export const createPlaylist = async (accessToken, userId) => {
  const nameData = {
    name: 'Accentify Playlist',
    description: 'Generated by Accentify.',
    public: true,
  };

  const response = await fetch(
    `https://api.spotify.com/v1/users/${userId}/playlists`,
    {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + accessToken,
      },
      body: JSON.stringify(nameData),
    }
  );

  if (!response.ok) {
    throw new Error('Fetching track info failed.');
  }

  const data = await response.json();
  return data;
};

// receives a uri string that is already preformatted
export const populatePlaylist = async (accessToken, playlistId, uri) => {
  const response = await fetch(
    `https://api.spotify.com/v1/playlists/${playlistId}/tracks?uris=${uri}`,
    {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + accessToken,
      },
      // body: JSON.stringify(nameData),
    }
  );

  if (!response.ok) {
    throw new Error('Adding to playlist failed');
  }

  const data = await response.json();
  return data;
};
